# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            gypsydave5
tagline:          'Learns to Code'
description:      'The blog of David Wickes, software developer'
url:              http://gypsydave5.com
baseurl:          /

author:
  name:           'David Wickes'
  url:            http://gypsydave5
  email:          dave@gypsydave5.com

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/gypsydave5
  username:       gypsydave5

twitter:
  url: https://twitter.com/gypsydave5
  handle: '@gypsydave5'
