# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the source branch
  push:
    branches: [ source ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-go@v1
     
     - name: install blawg
       run: go install github.com/gypsydave5/blawg/blawg

     - name: debugging
       run: |
         ls -l
         pwd
         echo $GOBIN
         echo $GOPATH
      
     - name: build site
       run: $GOBIN/blawg
       
     - name: publish to s3
       uses: jakejarvis/s3-sync-action@master
       with:
        args: --acl public-read --follow-symlinks --delete
       env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'site'      # optional: defaults to entire repository
       
   
